//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPproduct.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Инверторизация
    {
        public int ID { get; set; }
        public string Местонахождение { get; set; }
        public string Инвентарный_номер { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Администрирование Администрирование { get; set; }
    }
}
